version: '3.8'

services:
  db:
    image: postgres:16.1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: DB_PIPYD_DATABASE
      POSTGRES_USER: DB_PIPYD_USER
      POSTGRES_PASSWORD: DB_PIPYD_PASSWORD
    ports:
      - "5432:5432"

  web:
    image: my_django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
